-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 25-Out-2020 às 18:24
-- Versão do servidor: 10.4.13-MariaDB
-- versão do PHP: 7.4.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `jbc_noticias`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `noticias`
--

CREATE TABLE `noticias` (
  `idNoticia` int(11) NOT NULL,
  `Categoria` int(11) NOT NULL,
  `Titulo` text NOT NULL,
  `Subtitulo` text NOT NULL,
  `Materia` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `noticias`
--

INSERT INTO `noticias` (`idNoticia`, `Categoria`, `Titulo`, `Subtitulo`, `Materia`) VALUES
(1, 1, 'Novas baterias podem levar a carros elétricos com recarga instantânea', 'Nova formulação usa grafeno e \"fósforo negro\" em uma combinação que alia capacidade de carga e estabilidade', '&nbsp&nbsp&nbsp Pesquisadores na China desenvolveram uma nova formulação para baterias que poderá permitir a construção de carros elétricos que poderão ser recarregados muito mais rapidamente que os modelos atuais. Tão rápido quando o tempo necessário para encher o tanque de um veículo a combustão. <br>         O segredo está no uso de um material chamado \"fósforo negro\", que tem propriedades similares ao grafite. Quando átomos de grafite são interligados em uma camada com apenas um átomo de espessura, temos grafeno. Se o grafite for substituído pelo fósforo negro, temos um material chamado \"fosforeno\".  <br>         Assim como o grafeno, ele é um excelente condutor de eletricidade. Além disso, como tem mais elétrons que o carbono, o fósforo interage com mais átomos de lítio, outro componente das baterias. Mas em contraste ao grafeno, o fosforeno não forma uma \"folha\" plana: em vez disso ele tem picos e vales, o que acaba sendo algo benéfico, já que ajuda a transportar rapidamente íons de lítio para dentro e para fora do material.  <br>         O problema com o fosforeno é que, assim como outros materiais, ele se expande à medida que acumula íons de lítio, levando a uma falha estrutural que interrompe o fluxo de energia elétrica quando submetido a ciclos de carga e descarga. Eventualmente estas falhas se tornam numerosas o bastante para inutilizar a bateria.  <br>         O que os pesquisadores chineses fizeram foi misturar fósforo negro a 15% de grafite. O fósforo armazena a maior parte dos íons de lítio, e o grafite serve como um \"reforço\" para a estrutura.  <br>         \"O material recuperou 80% de sua capacidade total em menos de 10 minutos e tem uma vida útil de 2.000 ciclos de operação à temperatura ambiente, medidos em condições compatíveis com os processos de fabricação industrial\", disse o professor Sen Xin, do Instituto de Química da Academia Chinesa de Ciências, que foi o co-autor principal do estudo.  <br>         Segundo o professor Xin, se a produção em escala for atingida, seria possível produzir uma bateria de íons de lítio com uma densidade energética de 35 Watts/hora por kg. <br>         \"A combinação de alta capacidade energética, alta velocidade de carga e longo ciclo de vida é o santo graal da pesquisa de baterias, que é determinado por um de seus componentes-chave: os materiais usados nos eletrodos\", diz Hengxing Ji, professor da Universidade de Ciência e Tecnologia da China (USTC). <br>         \"Nosso objetivo é encontrar um material para eletrodos que possa causar um impacto na métrica de desempenho em pesquisas de laboratório, mas que seja capaz de cumprir sua promessa e atender às técnicas e requisitos da produção industrial\", diz. <br>  '),
(2, 1, 'Facebook força provedor a retirar site de grupo crítico do ar', 'O website do Real Facebook Oversight (RFOB) foi retirado do ar após denúncias de infringências à marca registrada da rede e suposto esquema de \"phishing\" para atrair pessoas falsamente ao website', '&nbsp&nbsp&nbsp O Facebook forçou a retirada do ar de um website pertencente a um grupo crítico à sua postura perante processos eleitorais. A alegação é de que o registro do domínio (realfacebookoversight.org) fere a utilização da marca registrada pela rede. <br>          O Real Facebook Oversight (RFOB) se consolidou como um dos principais grupos de oposição às ações da rede de Mark Zuckerberg, principalmente na influência de pleitos no mundo inteiro. Como seu nome indica, ele propõe realizar uma \"supervisão real\", em alusão a comissão de supervisão interna da empresa. <br>          A principal pauta do grupo é a influência do Facebook, e de outros aplicativos pertencentes ao conglomerado, em eleições por todo o mundo. De acordo com seus membros, que são em sua maioria ativistas, advogados e jornalistas, a rede social teria noção de que seu algorítimo vem influenciando em decisões majoritárias e não teria tomado ações sobre o fato <br>          A organização ganhou corpo e popularidade, e de acordo com apuração da Vice, o Facebook tentou agir pela derrubada de sua presença digital. Representantes da rede social entraram em contato com o provedor que hospeda o website, pedindo a retirada de todo seu conteúdo, alegando a utilização inadequada da marca no registro do domínio.  <br>          Por fim, o domínio foi suspenso por uso ilegal de marca registrada, com \"intuito de personificar o conglomerado de redes sociais americanas\", de acordo com  um e-mail recebido por Carole Cadwalladr, jornalista e participante da organização. <br>          Cadwalladr criticou abertamente a postura do Facebook na ação. \"Há um descaramento em ação aqui. Não é apenas que uma empresa que usou a \"liberdade de expressão\" como uma capa protetora iria atrás de nosso ISP e nos expulsaria da Internet, mas seu porta-voz oficial responde a essas críticas atacando e perseguindo jornalistas.\" <br>          <br><strong>Facebook nega ação de censura</strong><br><br>          O Facebook se pronunciou por meio de um porta-voz afirmando que a denúncia não teria partido do departamento legal da rede social. “Este site foi sinalizado automaticamente por um fornecedor porque continha a palavra \"facebook\" em seu domínio, e uma ação foi tomada sem nos consultar”. <br>'),
(3, 1, 'Após revelar iPhones, Apple libera versão final do iOS 14.1', 'Versão \"Golden Master\" chega primeiro aos desenvolvedores e costuma ser liberada aos usuários depois de pouco tempo', '&nbsp&nbsp&nbsp Além do iPhone 12, a Apple realizou outro anúncio importante que não passou tão percebido. A empresa lançou a primeira grande atualização do iOS 14, que chegou à versão 14.1. O update começou a ser distribuído na tarde desta terça-feira (13). <br>          A versão teve uma trajetória um pouco diferente das demais. A Apple não lançou versão beta do iOS 14.1 para sua comunidade de desenvolvedores e aficionados, fazendo com que seu lançamento fosse uma surpresa.  <br>          O lançamento, no entanto, não foi público. A empresa lançou a versão \"Golden Master\" do iOS 14.1, que é disponibilizada apenas para os participantes do programa de testes em beta. No entanto, a versão GM costuma ser definitiva e liberada a todos pouco tempo depois atingir esse público. Para referência, a GM do iOS 14 foi lançada apenas um dia antes do iOS 14 chegar a todos os usuários de iPhone. <br>          Estima-se que a decisão tinha como objetivo evitar o vazamento de informações sobre os novos iPhones. Há motivos para essa precaução; o site AppleInsider nota que o iOS 14.1 prepara o sistema operacional para funções novas do iPhone 12, como a gravação de vídeo em HDR e modos de câmera melhoradas. <br>          Como a Apple não publicou o changelog detalhado com todas as novidades do iOS 14.1, ainda não é possível descrever quais são todas as novidades da atualização. <br>         Junto do iOS 14.1, a Apple também liberou as versões GM de seus outros sistemas operacionais, incluindo o iPadOS 14.1, o tvOS 14.1. A companhia também lançou a terceira versão beta do iOS 14.2, do iPadOS 14.2, do tvOS 14.2 e do watchOS 7.1. <br> '),
(4, 1, 'Microsoft encerra suporte a versões antigas do Office nos Macs', 'Suporte ao Office 2010 e 2016 acaba nesta terça-feira (13); Microsoft recomenda usar novas versões do pacote de aplicativos', '&nbsp&nbsp&nbsp Esta terça-feira (13) marca o início de um novo iPhone, mas também marca o fim de uma era: é o último dia de suporte para Office 2010 e Office 2016 no Mac. Após as atualizações do Patch Tuesday de hoje, a Microsoft não fornecerá mais correções de bugs, updates de segurança ou suporte técnico para esses produtos. Ambos podem continuar sendo usados, mas não haverá mais suporte para resolver eventuais problemas. <br>         Além de alertar os usuários sobre o fim do suporte para essas duas versões do Office, a Microsoft também orienta seus clientes a usar o Office 2016, Office 2019 ou Microsoft 365 Apps (antes chamado de Office 365 Apps) para se conectar a serviços de back-end do Office 365. A empresa não impedirá que usuários de versões anteriores do Office se conectem aos serviços do Microsoft 365, mas alertou que quem o fizer não terá acesso a todos os recursos e atualizações mais recentes. <br>          A Microsoft anunciou em fevereiro de 2018 que usuários corporativos precisariam do Office 365 Pro Plus ou Office 2019 no suporte convencional para acessar os serviços de back-end do Office 365. Porém, devido ao feedback dos usuários, em setembro do mesmo ano a Microsoft mudou sua política, permitindo que os usuários continuassem a usar os serviços do Office 365 com o Office 2016. Essa mudança é válida até outubro de 2023, quando o acesso precisará ser feito por meio de versões mais recentes. <br>          Recentemente, a Microsoft anunciou que entregará uma nova versão sem assinatura do Office de Windows e Mac na segunda metade de 2021. Esses novos clientes permanentes do Office provavelmente receberão o nome Office 2022, supondo que a empresa siga os modelos de nomenclatura anteriores. Além disso, haverá outra versão dos servidores Office locais chegando no segundo semestre do próximo ano, mas exigirá uma assinatura para atualizações de segurança, correções e patches.<br>'),
(5, 2, 'Conchata Ferrell, atriz de \"Two and a half men\", morre aos 77 anos', 'Ela foi indicada a dois Emmy por sua atuação como Berta na comédia. De acordo com Deadline, atriz morreu por complicações causadas por uma parada cardíaca em hospital na Califórnia.', '&nbsp&nbsp A atriz Conchata Ferrell, conhecida por sua atuação como a diarista Berta na série \"Two and a half men\", morreu aos 77 anos nesta segunda-feira (12), de acordo com o site Deadline, por complicações causadas por uma parada cardíaca. <br>          De acordo com a agência de notícias Associated Press, a informação foi confirmada pela publicista Cynthia Snyder. Ferrell estava cercada pela família em um hospital na Califórnia, nos Estados Unidos. <br>         Ela recebeu duas indicações como atriz coadjuvante no Emmy por seu trabalho na série cômica, intitulada de \"Dois homens e meio\" no Brasil. <br>         Ela também foi indicada ao Emmy como atriz coadjuvante em drama por sua atuação em \"L.A. Law\", em 1992. <br>         Na TV, esteve em séries como \"Plantão Médico\", \"Buffy: A Caça-Vampiros\", \"Grace e Frankie\" e \"O rancho\". <br>         A atriz ainda fez trabalhos no cinema, em filmes como \"Edward Mãos de Tesoura\" (1990), \"Erin Brockovich, uma Mulher de Talento\" (2000) e \"A Herança de Mr. Deeds\" (2002). <br>         Em julho, o marido de Ferrell, Arnie Anderson, divulgou que ela estava internada desde maio depois de sofrer um infarto. <br>         A atriz passou mais de quatro semanas na unidade de terapia intensiva (UTI), e depois foi transferida a um centro de tratamento a longo prazo, onde ficou ligada a um respirador e fazia diálise. <br>'),
(6, 2, '\"Bacurau\" e \"A Vida Invisível\" são vencedores do Grande Prêmio do Cinema Brasileiro', '19ª edição da premiação aconteceu de forma remota por causa da pandemia de coronavírus e vencedores receberam troféus em casa. Silvero Pereira e Fabrício Boliveira dividiram prêmio de Melhor Ator. Veja mais ganhadores.', '&nbsp&nbsp&nbsp \"Bacurau\" e \"A Vida Invisível\" foram os grandes vencedores da 19ª edição do Grande Prêmio do Cinema Brasileiro. O evento aconteceu na noite deste domingo (11) de forma remota, por causa da pandemia de coronavírus. <br>         Segundo a produção do evento, o Troféu Grande Otelo será entregue diretamente na casa de cada um dos vencedores das 32 categorias do prêmio. <br>         Líder em indicações (15 no total), \"Bacurau\" levou a melhor em seis categorias. \"A vida invisível\", que disputava em 14 categorias, ficou com 5 prêmios. <br>         Silvero Pereira (\"Bacurau\") e Fabrício Boliveira (\"Simonal\") dividiram o prêmio na categoria de Melhor Ator. <br>         A premiação teve apresentação de Marina Person e Adriana Couto e contou com participações musicais de Paulinho Moska, Joyce Moreno, Francis Hime, Pedro Luís e Teresa Cristina. <br>         Diferente dos anos anteriores, o 19º Grande Prêmio do Cinema Brasileiro não homenageou uma personalidade em específico, mas todos os profissionais do setor audiovisual, coletivamente. <br>'),
(7, 2, 'Zé Manoel desnuda o coração em álbum influenciado pela escuta de discos de artistas negros', 'Compositor e pianista alinha nove canções em repertório autoral gravado com produção musical de Luisão Pereira.', '&nbsp&nbsp&nbsp Inicialmente intitulado Meu coração escuta e dita em silêncio, o terceiro álbum de estúdio do cantor, compositor e pianista Zé Manoel teve o nome trocado para Do meu coração nu e é com esse título definitivo – mais forte e mais sonoro – que o disco chega ao mercado fonográfico em 26 de outubro em edição da gravadora Joia Moderna. <br>         Uma semana antes, em 19 de outubro, o artista – pernambucano de Petrolina (PE) que voltou a morar no Recife (PE) após anos de residência na cidade de São Paulo (SP) – lança o single Adupé Obaluaê. <br>         Trata-se da segunda amostra do álbum produzido pelo guitarrista e baixista Luisão Pereira – com arranjos de Alberto Continentino, Rafael Marques e Stephane San Juan – e anunciado em junho com o single História antiga (Zé Manoel). <br>         O álbum Do meu coração nu alinha nove músicas no inédito repertório autoral. Notre historie (Zé Manoel e Stephane San Juan) e Pra iluminar o rolê (Zé Manoel) estão entre as composições do álbum gravado por Zé Manoel com participações da poeta pernambucana Bell Puã e da cantora baiana Luedji Luna. <br>         Em rede social, Zé Manoel esmiuçou as referências embutidas no pulso do álbum Do meu coração nu. “Lá em casa tinha um toca discos. Camila (Yasmine, amiga e conterrânea do artista) trazia vinis, quase sempre de artistas pretos e a gente passava tardes ouvindo música, conversando, sonhando. (Ela) me apresentou coisas que, na época, eu sequer imaginava que existiam. Balé folclórico da Bahia, Missa Luba, Os Cantores de Ébano. Lembro quando, anos mais tarde, ela chegou com o CD de Lauryn Hill, novidade quentinha, nos idos dos anos 2000. Pensei nesses encontros com Camila várias vezes durante a feitura do novo disco. É um disco dedicado a essas lembranças, dedicado aos irmãos e irmãs pretxs e indígenas, à música que eu ouvia, fora das aulas de piano, onde eu estudava Ernesto Nazareth, Chiquinha Gonzaga, Zequinha Abreu”, contextualiza Zé Manoel, a respeito desse primeiro álbum de estúdio e de músicas inéditas desde Canção e silêncio (2015), disco que deu projeção ao artista.  <br>'),
(8, 2, 'Filarmônica de Nova York cancela apresentações até junho de 2021 devido à pandemia', 'Deborah Borda, presidente da Filarmônica, diz que cancelamento \"não é apenas inédito, é devastador tanto para o estado de espírito dos músicos quanto do público\".', ' &nbsp&nbsp&nbsp A Orquestra Filarmônica de Nova York anunciou nesta-feira (13) o cancelamento de todos as suas apresentações até meados de junho de 2021, por causa da pandemia do coronavírus. Esta é a primeira vez que a instituição de 178 anos é forçada a cancelar uma temporada inteira <br>     A Filarmônica afirmou que tomou a decisão por conselho de autoridades médicas. Os teatros da Broadway e a Metropolitan Opera adotaram recentemente medidas semelhantes. <br>     A entidade prometeu continuar oferecendo conteúdo digital gratuito e disse que em breve anunciará uma série de concertos pré-gravados por pequenos grupos de membros da orquestra para o inverno e a primavera. <br>     O cancelamento de uma temporada inteira \"não é apenas inédito, é devastador tanto para o estado de espírito dos músicos quanto do público, e tem profundas consequências econômicas\", disse a presidente da Filarmônica, Deborah Borda, em nota. Mas \"não há outra opção\", acrescentou. <br>     Segundo Borda, a instituição pretende aproveitar o cancelamento da temporada para adiantar obras de US$ 550 milhões que começariam apenas em maio de 2022, a terceira etapa de uma grande reforma. <br>     À espera da nova temporada, a Filarmônica está planejando para a primavera de 2021 o retorno do projeto Bandwagon, que consiste em pequenos espetáculos externos em diferentes partes da cidade de Nova York. <br>     A primeira edição, realizada em agosto, foi um grande sucesso, embora o local do concerto não tenha sido divulgado com antecedência para evitar grandes aglomerações. <br>');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `noticias`
--
ALTER TABLE `noticias`
  ADD PRIMARY KEY (`idNoticia`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `noticias`
--
ALTER TABLE `noticias`
  MODIFY `idNoticia` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
